### ISSUE TITLE
PRACTICA 5

### ISSUE THREAD

**Issue by Sandra631** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Sandra631#2]
[PRACTICA5_TopicosAvanzados.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Sandra631/files/8348371/PRACTICA5_TopicosAvanzados.pdf)

**Comment by IrvingFernand0** [comment]
Esta practica obtuvo 95%
Correspondiente a **19** de calificación
Bien hecho :)

**Comment by josealfredo79** [comment]
Bien hecho y revisado....
